version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Download and install tflint
          command: |
            wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
      - run:
          name: Install dependencies
          command: apk add --update py-pip bash
      - run:
          name: Install aws-cli
          command: pip install awscli --upgrade --user
      - run:
          name: Lint the terraform code
          command: ./tflint --deep --aws-region us-east-1
      - run:
          name: Run terraform init
          command: terraform init -input=false test/integration
      - run:
          name: Run terraform plan
          command: terraform plan -out=tfplan -input=false test/integration
      - run:
          name: Run terraform apply
          command: terraform apply tfplan
      - run:
          name: Update NS and SOA records
          command: /bin/bash test/integration/scripts/ns.sh
      - run:
          name: Update registrar NS records
          command: /bin/bash test/integration/scripts/reg.sh
  test:
    docker:
      - image: gliderlabs/alpine:latest
    steps:
      - run:
          name: Install dependencies
          command: apk add --update bash bind-tools git ssh
      - checkout
      - run:
          name: Test DNS records
          command: /bin/bash test/integration/scripts/test.sh
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Run terraform init
          command: terraform init -input=false test/integration
      - run:
          name: Run terraform destroy
          command: terraform destroy -auto-approve test/integration
workflows:
  version: 2
  build_test_destroy:
    jobs:
      - build
      - test:
          requires:
            - build
      - destroy:
          requires:
            - test
